### ISSUE TITLE
LDAP does a 're-setup' after server reboot

### ISSUE THREAD

**Issue by TheJKM** [polarwinkel/SchoolConnect#20]
I did the following:

- setup philleconnect and create a user
- reboot server
- sudo docker-compose down
- sudo docker-compose up -d

now, I have the default users 'root' and 'nobody', but the user I created is missing. It's home-folder in /home/students/ is still there.

UPDATE: Samba also istn't working after that, but I think that's caused by the LDAP 're-setup'

**Comment by polarwinkel** [comment]
It seems to have been related to [Issue #1576 in docker-compose](https://github.com/docker/compose/issues/1576), I think I have fixed it in dev, could you confirm and close if it is running?

(I will hopefully get in touch with this container the next days to enable nginx auth with it and make it a little smoother then.)

**Comment by TheJKM** [comment]
Works perfectly, even rebooting the server without docker-compose down and up is now possible!

**Comment by TheJKM** [comment]
Still facing this issue on my physical test machine (Ubuntu Server 17.10), but not in my VM (Ubuntu Server 16.04). I executed dev/cleanup.sh and re-cloned the code, but after reboot the LDAP is still empty (and the containers are not running), while everything works in the VM.

**Comment by polarwinkel** [comment]
so the LDAP is empty after you start it?
Depending on your Docker-Installation the Docker-daemon might not start on system startup
If you execute `docker ps` and it takes a while until the running containers show the docker daemon first starts in the background. This would not be an issue of the containers, but with the individual docker-setup.
After you do this, are the Users you created still gone?

**Comment by TheJKM** [comment]
Ah ok, `docker ps` brings my containers back up, but the effect is similar to `docker-compose up -d`, LDAP still empty on that machine. Its weird, I will re-install it tomorrow when 18.04 LTS is out.

**Comment by polarwinkel** [comment]
In the compose-file the containers are set up to be restarted restart always, after reboot, crash, whatever. But if the system doesn't bring up the docker daemon, it can't start any container.
I think it's a default setting in Ubuntu 17.10 NOT to bring up docker on boot, I hope it'll be better with 18.04, we'll see...
But the empty LDAP is a different problem that is quite likely caused by the container start in the entrypoint.sh, I'll check it out and fix it the next days.

**Comment by TheJKM** [comment]
Empty LDAP just also happened in my VM

**Comment by TheJKM** [comment]
Ubuntu Server 18.04 changes nothing, neither empty LDAP nor autostart

**Comment by polarwinkel** [comment]
The lost user issue should be fixed, I think I forgot to remove some testing code, sorry...

Could you confirm and close it (again)?

The not starting docker daemon: I can confirm the issue and have been looking for solutions for a while with no success so far, but it is most likely an ubuntu-issue, I don't have the problem on my system with the docker-repository (which you'll find in most [docker-install-guides](https://docs.docker.com/install/linux/docker-ce/ubuntu/))

**Comment by TheJKM** [comment]
Works on my 18.04 VM, thanks!

**Comment by TheJKM** [comment]
Seems like I just tested `sudo docker-compose up -d`, after `sudo docker-compose up -d --build` it's empty again. But that would mean that a normal reboot is now fixed (?)

**Comment by polarwinkel** [comment]
ok, now I am sure I got it - but you better test it as well.

The problem:
when running `dpkg-reconfigure slapd` it will make a backup of the database, but doesn't put it back into place.
So I had the reconfigure only run if there is no database of the ldap already.
But without a reconfigure in a new container samba won't connect to it: The authentication failes. I assume the password is hashed with a different salt in a new container (or something like that).

I had it solved before, but didn't document my solution, so it got lost again because I didn't know anymore why I reconfiged a already configured ldap.
The advantage: Changing ldap-password in a running system might work now as well (not tested yet)

**Comment by TheJKM** [comment]
Works now!

**Comment by polarwinkel** [comment]
Concerning the autostart of the docker daemon on system boot:
Execute
`sudo systemctl enable docker.service`
to autostart docker, in newer versions (I think even the upstream repo of docker itself) this isn't the default for some reason.
I added a hint for this to the website as well.
